//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFormsExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoFormsExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепло
        ///Холод
        ///Свет
        ///Электролиз
        ///Кислород
        ///Водород
        ///Фтор
        ///Азот
        ///Хлор
        ///Углерод
        ///Сера
        ///Натрий
        ///Калий
        ///Кремний
        ///Фосфор
        ///Хром
        ///Барий
        ///Марганец
        ///Ртуть
        ///Алюминий
        ///Железо
        ///Медь
        ///Свинец
        ///Гелий
        ///Золото
        ///Озон
        ///БелыйФосфор
        ///ДигидрогенаМонооксид
        ///ПероксидВодорода
        ///МонооксидСеры
        ///ДиоксидСеры
        ///ТриоксидСеры
        ///УгарныйГаз
        ///УглекислыйГаз
        ///ОксидНатрия
        ///ОксидКалия
        ///СернаяКислота
        ///ПероксодисернаяКислота
        ///СолянаяКислота
        ///ХлорсульфоноваяКислота
        ///ХлоридНатрия
        ///ГипохлоритНатрия
        ///ГидроксидНатрия
        ///ГидросульфатНатрия
        ///АзотнаяКислота
        ///Аммиак
        ///УгольнаяКислота
        ///КарбонатНатрия
        ///Метакремн [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string facts {
            get {
                return ResourceManager.GetString("facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (deftemplate ioproxy		; шаблон факта-посредника для обмена информацией с GUI
        ///	(slot fact-id)		; теоретически тут id факта для изменения
        ///	(multislot answers)	; возможные ответы
        ///	(multislot messages)	; исходящие сообщения
        ///	(slot reaction)		; возможные ответы пользователя
        ///	(slot value)		; выбор пользователя
        ///	(slot restore)		; забыл зачем это поле
        ///)
        ///
        ///(deffacts proxy-fact
        ///	(ioproxy
        ///		(fact-id 0112)	; это поле пока что не задействовано
        ///		(value none)	; значение пустое
        ///		(messages)	; мультислот messag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string persons {
            get {
                return ResourceManager.GetString("persons", resourceCulture);
            }
        }
    }
}
